export const colors = [
{ value: 1, label: "Gold"},
{ value: 2, label: "Dark Blue"},
{ value: 3, label: "Lilac"},
{ value: 4, label: "Orange"},
{ value: 5, label: "Light Brown"},
{ value: 6, label: "Yellow"},
{ value: 7, label: "Tan"},
{ value: 8, label: "Wheaten"},
{ value: 9, label: "White"},
{ value: 10, label: "Dark Brown"},
{ value: 11, label: "Blue"},
{ value: 12, label: "Light Silver"},
{ value: 13, label: "Red"},
{ value: 14, label: "Cream"},
{ value: 15, label: "Black"},
{ value: 16, label: "Silver"},
{ value: 17, label: "Rust"},
{ value: 18, label: "Brown"},
{ value: 19, label: "Apricot"},
{ value: 20, label: "Fawn"},
{ value: 21, label: "Chestnut"},
{ value: 22, label: "Gray"},
{ value: 23, label: "Beige"},
{ value: 24, label: "Dark Brown and Gold Striped"},
{ value: 25, label: "Black Brown Brindle"},
{ value: 26, label: "Black and Tan Striped"},
{ value: 27, label: "Blue and Apricot Striped"},
{ value: 28, label: "Dark Brown and Light Brown Striped"},
{ value: 29, label: "Dark Brown and Apricot Striped"},
{ value: 30, label: "Black and Apricot Striped"},
{ value: 31, label: "Dark Brown and Tan Striped"},
{ value: 32, label: "Black and Light Brown Striped"},
{ value: 33, label: "White, Dark Brown, and Light Brown Striped"},
{ value: 34, label: "White, Black, and Light Brown Striped"},
{ value: 35, label: "White, Dark Brown, and Tan Striped"},
{ value: 36, label: "White, Black, and Tan Striped"},
{ value: 37, label: "White, Black, and Brown Striped"},
{ value: 38, label: "Black, Dark Brown, and Tan Striped"},
{ value: 39, label: "White, Black, and Dark Brown Striped"},
{ value: 40, label: "White and Red Dotted"},
{ value: 41, label: "White and Orange Dotted"},
{ value: 42, label: "Black and White Dotted"},
{ value: 43, label: "White, Dark Blue, and Gold Dotted"},
{ value: 44, label: "Black and Tan"},
{ value: 45, label: "Dark Blue and Gold"},
{ value: 46, label: "White and Gold"},
{ value: 47, label: "Black and Cream"},
{ value: 48, label: "White and Chestnut"},
{ value: 49, label: "Black and Orange"},
{ value: 50, label: "White and Dark Brown"},
{ value: 51, label: "Blue and Fawn"},
{ value: 52, label: "Tan and Apricot"},
{ value: 53, label: "White and Light Silver"},
{ value: 54, label: "Brown and Tan"},
{ value: 55, label: "Gray and Gold"},
{ value: 56, label: "Silver and Beige"},
{ value: 57, label: "Black and Rust"},
{ value: 58, label: "Dark Brown and Tan"},
{ value: 59, label: "Lilac and Orange"},
{ value: 60, label: "Black and Chestnut"},
{ value: 61, label: "White and Brown"},
{ value: 62, label: "White and Red"},
{ value: 63, label: "Black and Gold"},
{ value: 64, label: "White and Tan"},
{ value: 65, label: "Light Brown and Gold"},
{ value: 66, label: "Blue and Gold"},
{ value: 67, label: "White and Yellow"},
{ value: 68, label: "Light Silver and Dark Blue"},
{ value: 69, label: "White and Silver"},
{ value: 70, label: "White and Blue"},
{ value: 71, label: "Rust and Gold"},
{ value: 72, label: "Gray and Black"},
{ value: 73, label: "Black and Wheaten"},
{ value: 74, label: "White and Orange"},
{ value: 75, label: "Black and Light Brown"},
{ value: 76, label: "White and Dark Blue"},
{ value: 77, label: "Dark Brown and Gold"},
{ value: 78, label: "White and Black"},
{ value: 79, label: "Light Brown and Fawn"},
{ value: 80, label: "Blue and Apricot"},
{ value: 81, label: "Gold and Yellow"},
{ value: 82, label: "White and Rust"},
{ value: 83, label: "Black and Fawn"},
{ value: 84, label: "White and Apricot"},
{ value: 85, label: "Silver and Black"},
{ value: 86, label: "White and Fawn"},
{ value: 87, label: "Lilac and Apricot"},
{ value: 88, label: "Apricot and Cream"},
{ value: 89, label: "White and Beige"},
{ value: 90, label: "Blue and Dark Blue"},
{ value: 91, label: "White and Lilac"},
{ value: 92, label: "White and Light Brown"},
{ value: 93, label: "White and Gray"},
{ value: 94, label: "Black and Dark Brown"},
{ value: 95, label: "Black and Beige"},
{ value: 96, label: "White, Gray, and Black"},
{ value: 97, label: "White, Black, and Apricot"},
{ value: 98, label: "White, Light Brown, and Tan"},
{ value: 99, label: "White, Dark Blue, and Apricot"},
{ value: 100, label: "White, Black, and Light Brown"},
{ value: 101, label: "White, Black, and Beige"},
{ value: 102, label: "White, Dark Brown, and Gold"},
{ value: 103, label: "White, Silver, and Black"},
{ value: 104, label: "White, Gray, and Gold"},
{ value: 105, label: "White, Black, and Orange"},
{ value: 106, label: "White, Black, and Rust"},
{ value: 107, label: "White, Dark Blue, and Tan"},
{ value: 108, label: "White, Dark Blue, and Beige"},
{ value: 109, label: "White, Black, and Fawn"},
{ value: 110, label: "White, Black, and Gold"},
{ value: 111, label: "Blue, Black, and Yellow"},
{ value: 112, label: "White, Silver, and Beige"},
{ value: 113, label: "White, Lilac, and Dark Blue"},
{ value: 114, label: "White, Black, and Tan"},
{ value: 115, label: "Silver, Black, and Gold"},
{ value: 116, label: "White, Black, and Dark Brown"},
{ value: 117, label: "White, Light Silver, and Dark Blue"}]